import { Work_Sans, Inter , Montserrat} from "next/font/google";
import "./globals.css";
import "./globals.scss";

export const metadata = {
  title: "Your App Title",
  description: "A brief description of your app.",
  openGraph: {
    title: "Your App Title",
    description: "A brief description of your app.",
    url: "https://yourwebsite.com",
    images: [
      {
        url: "https://yourwebsite.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Your App Title",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Your App Title",
    description: "A brief description of your app.",
    images: ["https://yourwebsite.com/twitter-image.jpg"],
  },
};

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-work-sans",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
  display: "swap",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={`${workSans.variable} ${inter.variable} antialiased`}> */}
      {/* <body className={`${workSans.className} ${inter.className} antialiased`}> */}
      {/* <body className={`${workSans.className}  antialiased`}> */}
      {/* <body className={`${workSans.variable}  antialiased`}> */}
      <body className={`${workSans.className}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
 

export { workSans, inter, montserrat };




























// import { Work_Sans, Inter } from "next/font/google";
// import "./globals.css";
// import "./globals.scss";
// import 'bootstrap/dist/css/bootstrap.min.css';


// // const heebo = Heebo({ subsets: ['latin'], display: "swap", variable: '--font-Heebo', });


// const workSans = Work_Sans({
//   subsets: ['latin'],
//   weight: ['400', '500','600','700', '800', '900'],
//   variable: '--font-work-sans',
//   display: 'swap',
// });
// const inter = Inter({
//   subsets: ['latin'],
//   weight: ['400', '500','600','700', '800', '900'],
//   variable: '--font-inter',
//   display: 'swap',
// });


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${workSans.variable} ${inter.variable} antialiased`}>
//         {children}
//       </body>
//     </html>
//   );
// }
